image:
  repository: artifactory.dagility.com/docker/gith7-frontend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: ${project.prefix?lower_case}-${component.code}-${project.environment?lower_case}.${project.domain}
    paths:
    - /
serviceAccount:
  create: false
